// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTagToTask(arg1:number,arg2:number):Promise<void>;

export function CreateNewTag(arg1:models.TagDTO):Promise<models.TagDTO>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetAllTags():Promise<Array<models.TagDTO>>;

export function GetTagByID(arg1:number):Promise<models.TagDTO>;

export function GetTagsForTask(arg1:number):Promise<Array<models.TagDTO>>;

export function RemoveTagFromTask(arg1:number,arg2:number):Promise<void>;

export function UpdateTag(arg1:models.TagDTO):Promise<models.TagDTO>;
