// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewTag(arg1) {
  return window['go']['service']['TagsService']['CreateNewTag'](arg1);
}

export function GetTagByID(arg1) {
  return window['go']['service']['TagsService']['GetTagByID'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['service']['TagsService']['UpdateTag'](arg1);
}
