// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateNewTag(arg1:models.TagDTO):Promise<models.TagDTO>;

export function GetTagByID(arg1:number):Promise<models.TagDTO>;

export function UpdateTag(arg1:models.TagDTO):Promise<models.TagDTO>;
