// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToTask(arg1, arg2) {
  return window['go']['service']['TagsService']['AddTagToTask'](arg1, arg2);
}

export function CreateNewTag(arg1) {
  return window['go']['service']['TagsService']['CreateNewTag'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['service']['TagsService']['DeleteTag'](arg1);
}

export function GetAllTags() {
  return window['go']['service']['TagsService']['GetAllTags']();
}

export function GetTagByID(arg1) {
  return window['go']['service']['TagsService']['GetTagByID'](arg1);
}

export function GetTagsForTask(arg1) {
  return window['go']['service']['TagsService']['GetTagsForTask'](arg1);
}

export function RemoveTagFromTask(arg1, arg2) {
  return window['go']['service']['TagsService']['RemoveTagFromTask'](arg1, arg2);
}

export function UpdateTag(arg1) {
  return window['go']['service']['TagsService']['UpdateTag'](arg1);
}
