// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewTask(arg1) {
  return window['go']['service']['TaskService']['CreateNewTask'](arg1);
}

export function GetListByFilters(arg1) {
  return window['go']['service']['TaskService']['GetListByFilters'](arg1);
}

export function GetTaskByID(arg1) {
  return window['go']['service']['TaskService']['GetTaskByID'](arg1);
}
