// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateNewTask(arg1:models.TaskDTO):Promise<models.TaskDTO>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetListByFilters(arg1:models.TaskFilterDTO):Promise<Array<models.TaskDTO>>;

export function GetTaskByID(arg1:number):Promise<models.TaskDTO>;

export function UpdateTask(arg1:number,arg2:models.TaskDTO):Promise<models.TaskDTO>;
