// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateNewTask(arg1:models.TaskDTO):Promise<models.TaskDTO>;

export function GetListByFilters(arg1:models.TaskFilter):Promise<Array<models.TaskDTO>>;

export function GetTaskByID(arg1:number):Promise<models.TaskDTO>;
